### ISSUE TITLE
Можливо ворований template?

### ISSUE THREAD

**Issue by endlesskwazar** [hellhellpnick/front-end#1]
Знайшов ось такий репозиторій https://github.com/Rizraelle/tajem, теплейт дуже схожий на твій, або навпаки. Візуально 99% калька. Звісно ти можливо щось поправив, щось додав але все ж. Розкажи мені про історію створення твого темплейта.

**Comment by hellhellpnick** [comment]
Взяв макет на данному сайті
http://psd-html-css.ru/templates/tajam-besplatnyy-psd-shablon-lendingovoy-stranicy.
Так як він безкоштовний, то я його зробив. Якщо вас не влаштовує, могу
скинути макет, який робив на курсі.

пн, 13 апр. 2020 г. в 13:11, Skryl Aleksandr <notifications@github.com>:

**Comment by endlesskwazar** [comment]
Ок частково притензії знімаються. Просто поміняй теплейт так що унікальність пройшов, ребрендінг, кольорова гама щось накштаут такого.

**Comment by endlesskwazar** [comment]
+ на гілці journal-2020 в тебе тема не вибрана, я взагалі не знаю, що ти робиш. Якщо якась своя то просто додай цю тему в таблицю разом із своїм прізвищем.

**Comment by endlesskwazar** [comment]
Або стоп, просто в README вкажи силку на основі чого ти верстав. Не треба нічого перероблювати. Ну тему в журналі вкажи.

**Comment by hellhellpnick** [comment]
Тема фрилансера підійде?

**Comment by endlesskwazar** [comment]
fixed
